export const userPasswordBill = 'bbyb1873';

interface UserObject {
    excelHeaders: String[],
    referralSourceOptions: {value: String, label: String, color?: String}[],
    spheresOptions: {value: String, label: String, color?: String}[]
}
export const shittyDb:{ users: Array<{ user: string, password: string }>, billButkovich: UserObject, steveRemmels: UserObject } = {
    users: [{ user: 'billButkovich', password: 'bbyb1873'}, { user: 'steveRemmels', password: 'tempstevepass'}],
    billButkovich: {
        excelHeaders: [
            'Legal Plan #',
            'IDShield #',
            'CDLP #',
            'Small Buisness Plan #',
            'First Name (0r) Group Account Name',
            'Last Name',
            'Address',
            'Address 2',
            'Address 3',
            'Country',
            'City',
            'State',
            'Zip',
            'Email',
            'Home Phone',
            'Day Phone',
            'Cell Phone',
            'Birthday',
            'Annual Premium',
            'LegalShield Monthly Rate',
            'IDShield Monthly Rate',
            'CDLP Monthly Rate',
            'Small Biz Monthly Rate',
            'Plans Offered/Chosen',
            'Pay Periods',
            'Pay Period Amount',
            'Group Division',
            'Employee ID',
            'Production Date',
            'Effective Date',
            'Cancel Date',
            'Last Plan Amount',
            'Pre-Cancel',
            'Pending IDT',
            'Status (pick one)',
            'Referral Source (pick one)',
            'Language',
            'Group # ',
            'Company',
            'Spheres',
            'Contact Type'
        ],
        referralSourceOptions: [
            {value: ' ', label: 'None', color: '#FF5100'}, 
            {value: 'Association Member', label: 'Association Member' , color: '#FF5100'}, 
            {value: 'Association Referral', label: 'Association Referral', color: '#FF5100'}, 
            {value: 'Broker Referral', label: 'Broker Referral', color: '#FF5100'}, 
            {value: 'Broker Referral - A & H', label : 'Broker Referral - A & H' , color: '#FF5100'}, 
            {value: 'Insurance', label : 'Insurance', color: '#FF5100' },
            {value: 'Broker Referral - Barthuli Ins', label : 'Broker Referral - Barthuli Ins', color: '#FF5100' },
            {value: 'Group', label : 'Group', color: '#FF5100' },
            {value: 'Broker Referral - Chimienti & Assoc.', label : 'Broker Referral - Chimienti & Assoc.', color: '#FF5100' },
            {value: 'Broker Referral - Coast Benefits', label : 'Broker Referral - Coast Benefits' , color: '#FF5100'},
            {value: 'Broker Referral - PBT Benefits', label : 'Broker Referral - PBT Benefits', color: '#FF5100' }, // question is this combined with CHP
            {value: 'CHP', label : 'CHP', color: '#FF5100' },
            {value: 'Cold Call', label : 'Cold Call', color: '#FF5100' },
            {value: 'Conservation', label : 'Conservation' , color: '#FF5100'},
            {value: 'Current Group', label : 'Current Group', color: '#FF5100' },
            {value: "Dave's Group", label : "Dave's Group", color: '#FF5100' },
            {value: 'Drive By / Walk-In', label : 'Drive By / Walk-In', color: '#FF5100' },
            {value: 'FFL Referral', label : 'FFL Referral', color: '#FF5100' },
            {value: 'Friends and Family', label : 'Friends and Family' , color: '#FF5100'},
            {value: 'Google Ads', label : 'Google Ads', color: '#FF5100' },
            {value: 'Indian Health Clinics', label : 'Indian Health Clinics', color: '#FF5100' },
            {value: 'LinkedIn', label : 'LinkedIn' , color: '#FF5100'},
            {value: 'Networking Event', label : 'Networking Event' , color: '#FF5100'},
            {value: 'Partnership - Abe A.', label : 'Partnership - Abe A.' , color: '#FF5100'},
            {value: 'Partnership - Dave P.', label : 'Partnership - Dave P.' , color: '#FF5100'},
            {value: 'Partnership - Phil S.', label : 'Partnership - Phil S.', color: '#FF5100'},
            {value: 'Personal Friend/Business Referral', label: 'Personal Friend/Business Referral', color: '#FF5100'}
        ],
        spheresOptions: [
            {value: 'Association Member', label: 'Association Member', color: '#FF5100'}, 
            {value: 'Account', label: 'Account', color: '#FF5100'},
            {value: 'Aircraft / Aerospace', label: 'Aircraft / Aerospace', color: '#FF5100'},
            {value: 'Ambulance', label: 'Ambulance', color: '#FF5100'},
            {value: 'Associate - Past', label: 'Associate - Past', color: '#FF5100'},
            {value: 'Associate Prospects', label: 'Associate Prospects', color: '#FF5100'},
            {value: 'Association', label: 'Association', color: '#FF5100'},
            {value: 'Association Account', label: 'Association Account', color: '#FF5100'},
            {value: 'Attorneys', label: 'Attorneys', color: '#FF5100'},
            {value: 'Automotive', label: 'Automotive', color: '#FF5100'},
            {value: 'Broker', label: 'Broker', color: '#FF5100'},
            {value: 'Business Owner', label: 'Business Owner', color: '#FF5100'},
            {value: 'Business Partner', label: 'Business Partner', color: '#FF5100'},
            {value: 'Canceled', label: 'Canceled', color: '#FF5100'},
            {value: 'CHP Group', label: 'CHP Group', color: '#FF5100'},
            {value: 'Conservation', label: 'Conservation', color: '#FF5100'},
            {value: 'Construction', label: 'Construction', color: '#FF5100'},
            {value: 'Employee Benefits', label: 'Employee Benefits', color: '#FF5100'},
            {value: 'FFL', label: 'FFL', color: '#FF5100'},
            {value: "Finder's Fee", label: "Finder's Fee", color: '#FF5100'},
            {value: 'Fire Group', label: 'Fire Group', color: '#FF5100'},
            {value: 'Friends & Family', label: 'Friends & Family', color: '#FF5100'},
            {value: 'Government Agency', label: 'Government Agency', color: '#FF5100'},
            {value: 'Group', label: 'Group', color: '#FF5100'},
            {value: 'Id', label: 'Id', color: '#FF5100'},
            {value: 'Insurance', label: 'Insurance', color: '#FF5100'},
            {value: 'Insurance Agents', label: 'Insurance Agents', color: '#FF5100'},
            {value: 'Manufacturing', label: 'Manufacturing', color: '#FF5100'},
            {value: 'Medical Field', label: 'Medical Field', color: '#FF5100'},
            {value: 'Network', label: 'Network', color: '#FF5100'},
            {value: 'Police', label: 'Police', color: '#FF5100'},
            {value: 'Professional Sellers', label: 'Professional Sellers', color: '#FF5100'},
            {value: 'Prospect', label: 'Prospect', color: '#FF5100'},
            {value: 'SAS', label: 'SAS', color: '#FF5100'},
            {value: 'Schools / Education', label: 'Schools / Education', color: '#FF5100'},
            {value: 'Services', label: 'Services', color: '#FF5100'},
            {value: 'Small Business', label: 'Small Business', color: '#FF5100'},
            {value: 'Spanish', label: 'Spanish', color: '#FF5100'},
            {value: 'Tech', label: 'Tech', color: '#FF5100'},
            {value: 'Utilities', label: 'Utilities', color: '#FF5100'}
        ]
    },
    steveRemmels: {
        excelHeaders: [
            'Legal Plan #',
            'IDShield #',
            'CDLP #',
            'Small Buisness Plan #',
            'First Name (0r) Group Account Name',
            'Last Name',
            'Address',
            'Address 2',
            'Address 3',
            'Country',
            'City',
            'State',
            'Zip',
            'Email',
            'Home Phone',
            'Day Phone',
            'Cell Phone',
            'Birthday',
            'Annual Premium',
            'LegalShield Monthly Rate',
            'IDShield Monthly Rate',
            'CDLP Monthly Rate',
            'Small Biz Monthly Rate',
            'Plans Offered/Chosen',
            'Pay Periods',
            'Pay Period Amount',
            'Group Division',
            'Employee ID',
            'Production Date',
            'Effective Date',
            'Cancel Date',
            'Last Plan Amount',
            'Pre-Cancel',
            'Pending IDT',
            'Status (pick one)',
            'Referral Source (pick one)',
            'Language',
            'Group # ',
            'Company',
            'Spheres',
            'Contact Type'
        ],
        referralSourceOptions: [
            {value: ' ', label: 'None', color: '#FF5100'}, 
            {value: 'Nothing here 1', label: 'Nothing here 1' , color: '#FF5100'}, 
            {value: 'Nothing here 2', label: 'Nothing here 2', color: '#FF5100'}, 
            {value: 'Nothing here 3', label: 'Nothing here 3', color: '#FF5100'}, 
        ],
        spheresOptions: [
            {value: 'Association Member', label: 'Association Member', color: '#FF5100'}, 
            {value: 'Account', label: 'Account', color: '#FF5100'},
            {value: 'Aircraft / Aerospace', label: 'Aircraft / Aerospace', color: '#FF5100'},
            {value: 'Baby here', label: 'WAHHHHHHHHH', color: '#FF5100'},
            {value: 'Associate - Past', label: 'Associate - Past', color: '#FF5100'},
            {value: 'Associate Prospects', label: 'Associate Prospects', color: '#FF5100'},
            {value: 'Association', label: 'Association', color: '#FF5100'},
        ]
    }
}

export const completedPlanHeadersBill = [
    'Legal Plan #',
    'IDShield #',
    'CDLP #',
    'Small Buisness Plan #',
    'First Name (0r) Group Account Name',
    'Last Name',
    'Address',
    'Address 2',
    'Address 3',
    'Country',
    'City',
    'State',
    'Zip',
    'Email',
    'Home Phone',
    'Day Phone',
    'Cell Phone',
    'Birthday',
    'Annual Premium',
    'LegalShield Monthly Rate',
    'IDShield Monthly Rate',
    'CDLP Monthly Rate',
    'Small Biz Monthly Rate',
    'Plans Offered/Chosen',
    'Pay Periods',
    'Pay Period Amount',
    'Group Division',
    'Employee ID',
    'Production Date',
    'Effective Date',
    'Cancel Date',
    'Last Plan Amount',
    'Pre-Cancel',
    'Pending IDT',
    'Status (pick one)',
    'Referral Source (pick one)',
    'Language',
    'Group # ',
    'Company',
    'Spheres',
    'Contact Type'
]

export const referralSourceOptions = [
    {value: ' ', label: 'None', color: '#FF5100'}, 
    {value: 'Association Member', label: 'Association Member' , color: '#FF5100'}, 
    {value: 'Association Referral', label: 'Association Referral', color: '#FF5100'}, 
    {value: 'Broker Referral', label: 'Broker Referral', color: '#FF5100'}, 
    {value: 'Broker Referral - A & H', label : 'Broker Referral - A & H' , color: '#FF5100'}, 
    {value: 'Insurance', label : 'Insurance', color: '#FF5100' },
    {value: 'Broker Referral - Barthuli Ins', label : 'Broker Referral - Barthuli Ins', color: '#FF5100' },
    {value: 'Group', label : 'Group', color: '#FF5100' },
    {value: 'Broker Referral - Chimienti & Assoc.', label : 'Broker Referral - Chimienti & Assoc.', color: '#FF5100' },
    {value: 'Broker Referral - Coast Benefits', label : 'Broker Referral - Coast Benefits' , color: '#FF5100'},
    {value: 'Broker Referral - PBT Benefits', label : 'Broker Referral - PBT Benefits', color: '#FF5100' }, // question is this combined with CHP
    {value: 'CHP', label : 'CHP', color: '#FF5100' },
    {value: 'Cold Call', label : 'Cold Call', color: '#FF5100' },
    {value: 'Conservation', label : 'Conservation' , color: '#FF5100'},
    {value: 'Current Group', label : 'Current Group', color: '#FF5100' },
    {value: "Dave's Group", label : "Dave's Group", color: '#FF5100' },
    {value: 'Drive By / Walk-In', label : 'Drive By / Walk-In', color: '#FF5100' },
    {value: 'FFL Referral', label : 'FFL Referral', color: '#FF5100' },
    {value: 'Friends and Family', label : 'Friends and Family' , color: '#FF5100'},
    {value: 'Google Ads', label : 'Google Ads', color: '#FF5100' },
    {value: 'Indian Health Clinics', label : 'Indian Health Clinics', color: '#FF5100' },
    {value: 'LinkedIn', label : 'LinkedIn' , color: '#FF5100'},
    {value: 'Networking Event', label : 'Networking Event' , color: '#FF5100'},
    {value: 'Partnership - Abe A.', label : 'Partnership - Abe A.' , color: '#FF5100'},
    {value: 'Partnership - Dave P.', label : 'Partnership - Dave P.' , color: '#FF5100'},
    {value: 'Partnership - Phil S.', label : 'Partnership - Phil S.', color: '#FF5100'},
    {value: 'Personal Friend/Business Referral', label: 'Personal Friend/Business Referral', color: '#FF5100'}
]

export const spheresOptions = [
    {value: 'Association Member', label: 'Association Member'}, 
    {value: 'Account', label: 'Account'},
    {value: 'Aircraft / Aerospace', label: 'Aircraft / Aerospace'},
    {value: 'Ambulance', label: 'Ambulance'},
    {value: 'Associate - Past', label: 'Associate - Past'},
    {value: 'Associate Prospects', label: 'Associate Prospects'},
    {value: 'Association', label: 'Association'},
    {value: 'Association Account', label: 'Association Account'},
    {value: 'Attorneys', label: 'Attorneys'},
    {value: 'Automotive', label: 'Automotive'},
    {value: 'Broker', label: 'Broker'},
    {value: 'Business Owner', label: 'Business Owner'},
    {value: 'Business Partner', label: 'Business Partner'},
    {value: 'Canceled', label: 'Canceled'},
    {value: 'CHP Group', label: 'CHP Group'},
    {value: 'Conservation', label: 'Conservation'},
    {value: 'Construction', label: 'Construction'},
    {value: 'Employee Benefits', label: 'Employee Benefits'},
    {value: 'FFL', label: 'FFL'},
    {value: "Finder's Fee", label: "Finder's Fee"},
    {value: 'Fire Group', label: 'Fire Group'},
    {value: 'Friends & Family', label: 'Friends & Family'},
    {value: 'Government Agency', label: 'Government Agency'},
    {value: 'Group', label: 'Group'},
    {value: 'Id', label: 'Id'},
    {value: 'Insurance', label: 'Insurance'},
    {value: 'Insurance Agents', label: 'Insurance Agents'},
    {value: 'Manufacturing', label: 'Manufacturing'},
    {value: 'Medical Field', label: 'Medical Field'},
    {value: 'Network', label: 'Network'},
    {value: 'Police', label: 'Police'},
    {value: 'Professional Sellers', label: 'Professional Sellers'},
    {value: 'Prospect', label: 'Prospect'},
    {value: 'SAS', label: 'SAS'},
    {value: 'Schools / Education', label: 'Schools / Education'},
    {value: 'Services', label: 'Services'},
    {value: 'Small Business', label: 'Small Business'},
    {value: 'Spanish', label: 'Spanish'},
    {value: 'Tech', label: 'Tech'},
    {value: 'Utilities', label: 'Utilities'}
]

export const userPasswordSteveRemmels = 'tempBitchPass'