export const userPasswordBill = 'bbyb1873';

interface UserObject {
    [key: string]: any,
    userPref: { 
        refferalSourcePref: Object[]
        spheresOptionsPref: Object[]
    },
    excelHeaders: Object,
    referralSourceOptions: {value: String, label: String, color?: String}[],
    spheresOptions: {value: String, label: String, color?: String}[],
    settings: {
        openLogAfterConvert: boolean,
        alternateName: {
            useCompanyName: boolean,
            extraText: string,
            extraTextAtFront: boolean
        }
    }
}

export const shittyDb:{[index: string]: any, users: Array<{[key: string]: any, user: string, password: string }>, billButkovich: UserObject } = {
    users: [{ user: 'billButkovich', password: 'bbyb1873'}, { user: 'steveRemmels', password: 'tempstevepass'}, { user: 'guest', password: 'guest' }],
    billButkovich: {
        userPref: {
            refferalSourcePref: [],
            spheresOptionsPref: [{value: 'Employee Benefits', label: 'Employee Benefits', color: '#FF5100'}, {value: 'English', label: 'English', color: '#FF5100'},]
        },
        excelHeaders: { // this is the modular mapping 
            'Legal Plan #': 'Legal Plan #',
            'IDShield #': 'IDShield #',
            'CDLP #': 'CDLP #',
            'Small Buisness Plan #': 'Small Buisness Plan #',
            'First Name (0r) Group Account Name': 'First Name',
            'Last Name': 'Last Name',
            'Address': 'Address 1',
            'Address 2': 'Address 2',
            'Address 3': 'Address 3',
            'Country': 'Country',
            'City': 'City',
            'State': 'State/Province',
            'Zip': 'Zip/Postal Code',
            'Email': 'Email',
            'Home Phone': 'Home Phone',
            'Day Phone': 'Day Phone',
            'Cell Phone': 'Cell Phone',
            'Birthday': 'Date of Birth',
            'Annual Premium': 'Annual Premium',
            'LegalShield Monthly Rate': 'Legal Shield Monthly Rate',
            'IDShield Monthly Rate': 'IDShield Monthly Rate',
            'CDLP Monthly Rate': 'CDLP Monthly Rate',
            'Small Biz Monthly Rate': 'Small Biz Monthly Rate',
            'Plans Offered/Chosen': 'Plans Offered/Chosen',
            'Pay Periods': 'Pay Period',
            'Pay Period Amount': 'Pay Period Amount',
            'Group Division': 'Group Division',
            'Employee ID': 'Employee ID',
            'Production Date': 'Production Date',
            'Effective Date': 'Effective Date',
            'Cancel Date': 'Cancel Date',
            'Last Plan Amount': 'Last Plan Amount Update',
            'Pre-Cancel': 'Pre-Cancel',
            'Pending IDT': 'Pending IDT',
            'Status (pick one)': 'Status',
            'Referral Source (pick one)': 'Referral Source',
            'Language': 'Language',
            'Group # ': 'Group #',
            'Company': 'Company',
            'Spheres': 'Spheres',
            // 'Contact Type': "Don't know what to connect to" // Do I need
        },
        referralSourceOptions: [
            {value: ' ', label: 'None', color: '#a5a8b1'}, 
            {value: 'Association Member', label: 'Association Member' , color: '#a5a8b1'}, 
            {value: 'Association Referral', label: 'Association Referral', color: '#a5a8b1'}, 
            {value: 'Broker Referral', label: 'Broker Referral', color: '#a5a8b1'}, 
            {value: 'Broker Referral - A & H', label : 'Broker Referral - A & H' , color: '#a5a8b1'}, 
            {value: 'Insurance', label : 'Insurance', color: '#a5a8b1' },
            {value: 'Broker Referral - Barthuli Ins', label : 'Broker Referral - Barthuli Ins', color: '#a5a8b1' },
            {value: 'Group', label : 'Group', color: '#a5a8b1' },
            {value: 'Broker Referral - Chimienti & Assoc.', label : 'Broker Referral - Chimienti & Assoc.', color: '#a5a8b1' },
            {value: 'Broker Referral - Coast Benefits', label : 'Broker Referral - Coast Benefits' , color: '#a5a8b1'},
            {value: 'Broker Referral - PBT Benefits', label : 'Broker Referral - PBT Benefits', color: '#a5a8b1' }, // question is this combined with CHP
            {value: 'CHP', label : 'CHP', color: '#a5a8b1' },
            {value: 'Cold Call', label : 'Cold Call', color: '#a5a8b1' },
            {value: 'Conservation', label : 'Conservation' , color: '#a5a8b1'},
            {value: 'Current Group', label : 'Current Group', color: '#a5a8b1' },
            {value: "Dave's Group", label : "Dave's Group", color: '#a5a8b1' },
            {value: "Abe`s Group", label : "Abe's Group", color: '#a5a8b1' },
            {value: 'Drive By / Walk-In', label : 'Drive By / Walk-In', color: '#a5a8b1' },
            {value: 'FFL Referral', label : 'FFL Referral', color: '#a5a8b1' },
            {value: 'Friends and Family', label : 'Friends and Family' , color: '#a5a8b1'},
            {value: 'Google Ads', label : 'Google Ads', color: '#a5a8b1' },
            {value: 'Indian Health Clinics', label : 'Indian Health Clinics', color: '#a5a8b1' },
            {value: 'LinkedIn', label : 'LinkedIn' , color: '#a5a8b1'},
            {value: 'Networking Event', label : 'Networking Event' , color: '#a5a8b1'},
            {value: 'Partnership - Abe A.', label : 'Partnership - Abe A.' , color: '#a5a8b1'},
            {value: 'Partnership - Dave P.', label : 'Partnership - Dave P.' , color: '#a5a8b1'},
            {value: 'Partnership - Phil S.', label : 'Partnership - Phil S.', color: '#a5a8b1'},
            {value: 'Personal Friend/Business Referral', label: 'Personal Friend/Business Referral', color: '#a5a8b1'}
        ],
        spheresOptions: [
            {value: 'Association Member', label: 'Association Member', color: '#a5a8b1'}, 
            {value: 'Account', label: 'Account', color: '#a5a8b1'},
            {value: 'Aircraft / Aerospace', label: 'Aircraft / Aerospace', color: '#a5a8b1'},
            {value: 'Ambulance', label: 'Ambulance', color: '#a5a8b1'},
            {value: 'Associate - Past', label: 'Associate - Past', color: '#a5a8b1'},
            {value: 'Associate Prospects', label: 'Associate Prospects', color: '#a5a8b1'},
            {value: 'Association', label: 'Association', color: '#a5a8b1'},
            {value: 'Association Account', label: 'Association Account', color: '#a5a8b1'},
            {value: 'Attorneys', label: 'Attorneys', color: '#a5a8b1'},
            {value: 'Automotive', label: 'Automotive', color: '#a5a8b1'},
            {value: 'Broker', label: 'Broker', color: '#a5a8b1'},
            {value: 'Business Owner', label: 'Business Owner', color: '#a5a8b1'},
            {value: 'Business Partner', label: 'Business Partner', color: '#a5a8b1'},
            {value: 'Canceled', label: 'Canceled', color: '#a5a8b1'},
            {value: 'CHP Group', label: 'CHP Group', color: '#a5a8b1'},
            {value: 'Conservation', label: 'Conservation', color: '#a5a8b1'},
            {value: 'Construction', label: 'Construction', color: '#a5a8b1'},
            {value: 'Employee Benefits', label: 'Employee Benefits', color: '#a5a8b1'},
            {value: 'English', label: 'English', color: '#a5a8b1'},
            {value: 'FFL', label: 'FFL', color: '#a5a8b1'},
            {value: "Finder's Fee", label: "Finder's Fee", color: '#a5a8b1'},
            {value: 'Fire Group', label: 'Fire Group', color: '#a5a8b1'},
            {value: 'Friends & Family', label: 'Friends & Family', color: '#a5a8b1'},
            {value: 'Government Agency', label: 'Government Agency', color: '#a5a8b1'},
            {value: 'Group', label: 'Group', color: '#a5a8b1'},
            {value: 'Id', label: 'Id', color: '#a5a8b1'},
            {value: 'Insurance', label: 'Insurance', color: '#a5a8b1'},
            {value: 'Insurance Agents', label: 'Insurance Agents', color: '#a5a8b1'},
            {value: 'Manufacturing', label: 'Manufacturing', color: '#a5a8b1'},
            {value: 'Medical Field', label: 'Medical Field', color: '#a5a8b1'},
            {value: 'Network', label: 'Network', color: '#a5a8b1'},
            {value: 'Police', label: 'Police', color: '#a5a8b1'},
            {value: 'Professional Sellers', label: 'Professional Sellers', color: '#a5a8b1'},
            {value: 'Prospect', label: 'Prospect', color: '#a5a8b1'},
            {value: 'SAS', label: 'SAS', color: '#a5a8b1'},
            {value: 'Schools / Education', label: 'Schools / Education', color: '#a5a8b1'},
            {value: 'Services', label: 'Services', color: '#a5a8b1'},
            {value: 'Small Business', label: 'Small Business', color: '#a5a8b1'},
            {value: 'Spanish', label: 'Spanish', color: '#a5a8b1'},
            {value: 'Tech', label: 'Tech', color: '#a5a8b1'},
            {value: 'Utilities', label: 'Utilities', color: '#a5a8b1'}
        ],
        settings: {
            openLogAfterConvert: true,
            alternateName: {
                useCompanyName: false,
                extraText: '',
                extraTextAtFront: false
            }
        }
    },
    guest: {
        userPref: {
            refferalSourcePref: [],
            spheresOptionsPref: [{value: 'Employee Benefits', label: 'Employee Benefits', color: '#FF5100'}, {value: 'English', label: 'English', color: '#FF5100'},]
        },
        excelHeaders: { // this is the modular mapping 
            'Legal Protection': 'Legal Plan',
            'ID Protection': 'ID Protection',
            'Car Protection': 'Car Protection',
            'Small Buisness Protection': 'Small Buisness Protection',
            'First Name (0r) Group Account Name': 'First Name',
            'Last Name': 'Last Name',
            'Address': 'Address 1',
            'Address 2': 'Address 2',
            'Address 3': 'Address 3',
            'Country': 'Country',
            'City': 'City',
            'State': 'State/Province',
            'Zip': 'Zip/Postal Code',
            'Email': 'Email',
            'Home Phone': 'Home Phone',
            'Day Phone': 'Day Phone',
            'Cell Phone': 'Cell Phone',
            'Birthday': 'Date of Birth',
            'Annual Premium': 'Annual Premium',
            'LegalShield Monthly Rate': 'Legal Shield Monthly Rate',
            'IDShield Monthly Rate': 'IDShield Monthly Rate',
            'CDLP Monthly Rate': 'CDLP Monthly Rate',
            'Small Biz Monthly Rate': 'Small Biz Monthly Rate',
            'Plans Offered/Chosen': 'Plans Offered/Chosen',
            'Pay Periods': 'Pay Period',
            'Pay Period Amount': 'Pay Period Amount',
            'Group Division': 'Group Division',
            'Employee ID': 'Employee ID',
            'Production Date': 'Production Date',
            'Effective Date': 'Effective Date',
            'Cancel Date': 'Cancel Date',
            'Last Plan Amount': 'Last Plan Amount Update',
            'Pre-Cancel': 'Pre-Cancel',
            'Pending IDT': 'Pending IDT',
            'Status (pick one)': 'Status',
            'Referral Source (pick one)': 'Referral Source',
            'Language': 'Language',
            'Group # ': 'Group #',
            'Company': 'Company',
            'Spheres': 'Spheres'
        },
        referralSourceOptions: [
            {value: ' ', label: 'None', color: '#FF5100'}, 
            {value: 'Association Member', label: 'Association Member' , color: '#FF5100'}, 
            {value: 'Association Referral', label: 'Association Referral', color: '#FF5100'}, 
            {value: 'Broker Referral', label: 'Broker Referral', color: '#FF5100'}, 
            {value: 'Broker Referral - A & H', label : 'Broker Referral - A & H' , color: '#FF5100'}, 
            {value: 'Insurance', label : 'Insurance', color: '#FF5100' },
            {value: 'Broker Referral - Barthuli Ins', label : 'Broker Referral - Barthuli Ins', color: '#FF5100' },
            {value: 'Group', label : 'Group', color: '#FF5100' },
            {value: 'Broker Referral - Chimienti & Assoc.', label : 'Broker Referral - Chimienti & Assoc.', color: '#FF5100' },
            {value: 'Broker Referral - Coast Benefits', label : 'Broker Referral - Coast Benefits' , color: '#FF5100'},
            {value: 'Broker Referral - PBT Benefits', label : 'Broker Referral - PBT Benefits', color: '#FF5100' }, // question is this combined with CHP
            {value: 'CHP', label : 'CHP', color: '#FF5100' },
            {value: 'Cold Call', label : 'Cold Call', color: '#FF5100' },
            {value: 'Conservation', label : 'Conservation' , color: '#FF5100'},
            {value: 'Current Group', label : 'Current Group', color: '#FF5100' },
            {value: "Dave's Group", label : "Dave's Group", color: '#FF5100' },
            {value: "Abe`s Group", label : "Abe's Group", color: '#FF5100' },
            {value: 'Drive By / Walk-In', label : 'Drive By / Walk-In', color: '#FF5100' },
            {value: 'FFL Referral', label : 'FFL Referral', color: '#FF5100' },
            {value: 'Friends and Family', label : 'Friends and Family' , color: '#FF5100'},
            {value: 'Google Ads', label : 'Google Ads', color: '#FF5100' },
            {value: 'Indian Health Clinics', label : 'Indian Health Clinics', color: '#FF5100' },
            {value: 'LinkedIn', label : 'LinkedIn' , color: '#FF5100'},
            {value: 'Networking Event', label : 'Networking Event' , color: '#FF5100'},
            {value: 'Partnership - Abe A.', label : 'Partnership - Abe A.' , color: '#FF5100'},
            {value: 'Partnership - Dave P.', label : 'Partnership - Dave P.' , color: '#FF5100'},
            {value: 'Partnership - Phil S.', label : 'Partnership - Phil S.', color: '#FF5100'},
            {value: 'Personal Friend/Business Referral', label: 'Personal Friend/Business Referral', color: '#FF5100'}
        ],
        spheresOptions: [
            {value: 'Association Member', label: 'Association Member', color: '#FF5100'}, 
            {value: 'Account', label: 'Account', color: '#FF5100'},
            {value: 'Aircraft / Aerospace', label: 'Aircraft / Aerospace', color: '#FF5100'},
            {value: 'Ambulance', label: 'Ambulance', color: '#FF5100'},
            {value: 'Associate - Past', label: 'Associate - Past', color: '#FF5100'},
            {value: 'Associate Prospects', label: 'Associate Prospects', color: '#FF5100'},
            {value: 'Association', label: 'Association', color: '#FF5100'},
            {value: 'Association Account', label: 'Association Account', color: '#FF5100'},
            {value: 'Attorneys', label: 'Attorneys', color: '#FF5100'},
            {value: 'Automotive', label: 'Automotive', color: '#FF5100'},
            {value: 'Broker', label: 'Broker', color: '#FF5100'},
            {value: 'Business Owner', label: 'Business Owner', color: '#FF5100'},
            {value: 'Business Partner', label: 'Business Partner', color: '#FF5100'},
            {value: 'Canceled', label: 'Canceled', color: '#FF5100'},
            {value: 'CHP Group', label: 'CHP Group', color: '#FF5100'},
            {value: 'Conservation', label: 'Conservation', color: '#FF5100'},
            {value: 'Construction', label: 'Construction', color: '#FF5100'},
            {value: 'Employee Benefits', label: 'Employee Benefits', color: '#FF5100'},
            {value: 'English', label: 'English', color: '#FF5100'},
            {value: 'FFL', label: 'FFL', color: '#FF5100'},
            {value: "Finder's Fee", label: "Finder's Fee", color: '#FF5100'},
            {value: 'Fire Group', label: 'Fire Group', color: '#FF5100'},
            {value: 'Friends & Family', label: 'Friends & Family', color: '#FF5100'},
            {value: 'Government Agency', label: 'Government Agency', color: '#FF5100'},
            {value: 'Group', label: 'Group', color: '#FF5100'},
            {value: 'Id', label: 'Id', color: '#FF5100'},
            {value: 'Insurance', label: 'Insurance', color: '#FF5100'},
            {value: 'Insurance Agents', label: 'Insurance Agents', color: '#FF5100'},
            {value: 'Manufacturing', label: 'Manufacturing', color: '#FF5100'},
            {value: 'Medical Field', label: 'Medical Field', color: '#FF5100'},
            {value: 'Network', label: 'Network', color: '#FF5100'},
            {value: 'Police', label: 'Police', color: '#FF5100'},
            {value: 'Professional Sellers', label: 'Professional Sellers', color: '#FF5100'},
            {value: 'Prospect', label: 'Prospect', color: '#FF5100'},
            {value: 'SAS', label: 'SAS', color: '#FF5100'},
            {value: 'Schools / Education', label: 'Schools / Education', color: '#FF5100'},
            {value: 'Services', label: 'Services', color: '#FF5100'},
            {value: 'Small Business', label: 'Small Business', color: '#FF5100'},
            {value: 'Spanish', label: 'Spanish', color: '#FF5100'},
            {value: 'Tech', label: 'Tech', color: '#FF5100'},
            {value: 'Utilities', label: 'Utilities', color: '#FF5100'}
        ],
        settings: {
            openLogAfterConvert: true,
            alternateName: {
                useCompanyName: false,
                extraText: '',
                extraTextAtFront: false
            }
        }
    },

}
/* Template */

// { user: 'user', password: 'userPass'}

// user: {
//     userPref: {
//         refferalSourcePref: [],
//         spheresOptionsPref: []
//     },
//     excelHeaders: [
//         'Legal Plan #',
//         'IDShield #',
//         'CDLP #',
//         'Small Buisness Plan #',
//         'First Name (0r) Group Account Name',
//         'Last Name',
//         'Address',
//         'Address 2',
//         'Address 3',
//         'Country',
//         'City',
//         'State',
//         'Zip',
//         'Email',
//         'Home Phone',
//         'Day Phone',
//         'Cell Phone',
//         'Birthday',
//         'Annual Premium',
//         'LegalShield Monthly Rate',
//         'IDShield Monthly Rate',
//         'CDLP Monthly Rate',
//         'Small Biz Monthly Rate',
//         'Plans Offered/Chosen',
//         'Pay Periods',
//         'Pay Period Amount',
//         'Group Division',
//         'Employee ID',
//         'Production Date',
//         'Effective Date',
//         'Cancel Date',
//         'Last Plan Amount',
//         'Pre-Cancel',
//         'Pending IDT',
//         'Status (pick one)',
//         'Referral Source (pick one)',
//         'Language',
//         'Group # ',
//         'Company',
//         'Spheres',
//         'Contact Type'
//     ],
//     referralSourceOptions: [
//         {value: ' ', label: 'None', color: '#FF5100'}, 
//         {value: 'Nothing here 1', label: 'Nothing here 1' , color: '#FF5100'}, 
//         {value: 'Nothing here 2', label: 'Nothing here 2', color: '#FF5100'}, 
//         {value: 'Nothing here 3', label: 'Nothing here 3', color: '#FF5100'}, 
//     ],
//     spheresOptions: [
//         {value: 'Association Member', label: 'Association Member', color: '#FF5100'}, 
//         {value: 'Account', label: 'Account', color: '#FF5100'},
//         {value: 'Aircraft / Aerospace', label: 'Aircraft / Aerospace', color: '#FF5100'},
//         {value: 'Baby here', label: 'WAHHHHHHHHH', color: '#FF5100'},
//         {value: 'Associate - Past', label: 'Associate - Past', color: '#FF5100'},
//         {value: 'Associate Prospects', label: 'Associate Prospects', color: '#FF5100'},
//         {value: 'Association', label: 'Association', color: '#FF5100'},
//     ],
//     settings: {
//         openLogAfterConvert: true,
//         alternateName: {
//             useCompanyName: false,
//             extraText: '',
//             extraTextAtFront: false
//         }
//     }
// }

/* LOOKS LIKE REMOVE */


export const userPasswordSteveRemmels = 'tempBitchPass'